name: Run Tests

on:
  push:
    branches: [task-01]
  pull_request:
    branches: [task-01]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Run individual tests
        run: |
          # Запускаем тесты из каждой директории отдельно
          for task_dir in sem_01/task_*/; do
            echo "Running tests in $task_dir"
            cd "$task_dir"
            python -m pytest test.py -v || echo "Test failed in $task_dir"
            cd ../../..
          done
