name: Run Tests

on:
  push:
    branches: [task-01]
  pull_request:
    branches: [task-01]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
