name: Python Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Determine changed files
        id: changed-files
        uses: tj-actions/changed-files@v14
        with:
          files: |
            sem_01/task_*/solution.py

      - name: Run tests for changed tasks
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            task_dir=$(dirname "$file")
            echo "Running tests for $task_dir"
            pytest "$task_dir/test.py" -v
          done

      - name: Run all tests if no specific task files changed
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          pytest sem_01/task_*/test.py -v
